#'ZeroDRM
#'
#' @description
#' Many statistical applications naturally produce semicontinuous data with a mixture of excessive zero values and skewed positive outcomes.
#' \insertCite{yuan2020zeros;textual}{ZeroDRM} proposed semiparametric inference procedures for the functionals of two semicontinuous populations under density ratio model (DRM).
#' Based on the results of functinals, \insertCite{yuan2021Gini;textual}{ZeroDRM} studied the inference of Gini indices of of two semicontinuous populations under the DRM.
#' The proposed method are also applicable to cases when there is no excess of zero values.
#' @description This package contains functions to make inference on the functionals and Gini indices of two populations under the DRM, including point estimation and confidence interval construction.
#'
#' @details
#' Suppose that two independent samples are generated by the following mixture models:
#' \deqn{X_{i1},\cdots, X_{in_i} \sim F_i(x)= \nu_iI(x \geq 0)+(1-\nu_i)I(x>0)G_i(x), \quad \mbox{for~}~i=0,1,}
#' where \eqn{\nu_i\in (0,1)}, \eqn{n_i} is the sample size for the \eqn{i}th sample,
#' \eqn{I(\cdot)} is an indicator function, and the \eqn{G_i}'s are the cumulative distribution functions (CDFs) of
#' the positive observations in the \eqn{i}th sample.
#'
#' To incorporate the information from both samples,
#' \insertCite{yuan2020zeros,yuan2021Gini;textual}{ZeroDRM} linked the two CDFs \eqn{G_0} and \eqn{G_1} in mixture model via a DRM:
#' \deqn{dG_1(x) = \exp\{\alpha + \boldsymbol{\beta}^\top \boldsymbol{q}(x)\}dG_0(x) = \exp\{\boldsymbol{\theta}^\top \boldsymbol{Q}(x)\}dG_0(x),}
#' where \eqn{dG_i} denote the density of \eqn{G_i}; \eqn{\boldsymbol{\theta} = (\alpha,\boldsymbol{\beta}^\top)^\top} are unknown parameters for the DRM;
#' \eqn{\boldsymbol{Q}(x) = (1,\boldsymbol{q}(x)^\top)^\top} with \eqn{\boldsymbol{q}(x)} being a pre-specified, non-trivial function of dimension \eqn{d};
#'the baseline distribution \eqn{F_0} is unspecified.
#'
#'@details
#' This package contains the following material:
#' \itemize{
#' \item The Density Ratio Model (\code{\link{drmCoef}}): a function to fit the DRM.
#' \item The inference on the functional (\code{\link{ZeroFunc}}): a function to estimate the functionals and construct the confidence interval under the DRM.
#' \item The inference on the mean ratio (\code{\link{MeanRatio}}): a function to estimate the mean ratio of two populations and construct the confidence interval under the DRM.
#' \item The inference on the Gini indices (\code{\link{ZeroGini}}): a function to estimate the Gini indices and construct the confidence intervals under the DRM.
#' \item The inference on the difference of two Gini indices (\code{\link{DiffGini}}): a function to estimate the difference of Gini indices of two populations and construct the confidence intervals under the DRM.
#' }
#'
#' @references
#'
#' \insertRef{yuan2020zeros}{ZeroDRM}
#'
#'\insertRef{yuan2021Gini}{ZeroDRM}
#' @docType package
#' @name ZeroDRM-package
NULL
